name: .NET

on:
  push:
    branches: [ master, develop, feature/legion ]
  pull_request:
    branches: [ master, develop, feature/legion ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: create-env-json
      uses: schdck/create-env-json@v1
      with:
        file-name: '/TauriApiWrapperTests/settings.json'
        APIKEY: ${{ secrets.APIKEY }}
        APISECRET: ${{ secrets.APISECRET }}
    - name: Build
      run: dotnet build --configuration Debug --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
