name: .NET Core

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Debug --no-restore
    - name: create-env-json
      uses: schdck/create-env-json@v1
      with:
        file-name: '/home/runner/work/TauriApiWrapper/TauriApiWrapper/TauriApiWrapperTests/bin/Debug/netcoreapp3.1/settings.json'
        apiKey: ${{ secrets.APIKEY }}
        apiSecret: ${{ secrets.APISECRET }}
    - name: Test
      run: dotnet test --no-restore --verbosity normal
